apiVersion: apps/v1
kind: Deployment
metadata:
  name:	harmonizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harmonizer
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
            app: harmonizer
    spec:
      hostAliases:
        - ip: "10.0.88.76"
          hostnames:
            - "master1.internal"
        - ip: "10.0.87.95"
          hostnames:
            - "master2.internal"
        - ip: "10.0.88.132"
          hostnames:
            - "worker1.internal"
        - ip: "10.0.86.33"
          hostnames:
            - "worker2.internal"
        - ip: "10.0.87.145"
          hostnames:
            - "worker3.internal"
        - ip: "10.0.86.214"
          hostnames:
            - "worker4.internal"
        - ip: "10.0.129.220"
          hostnames:
            - "kafka1.internal"
      containers:
        - name: harmonizer
          image: docker.tech.beegroup-cimne.com/jobs/importing_tool:latest
          command: ["python3", "-m", "harmonizer"]
          #command: ["/bin/sh", "-ec", "sleep 1000"]
          volumeMounts:
          - name: entrack-harmonize-secret
            mountPath: /home/ubuntu/bigg_entrack/config.json
            subPath: config.json
          - name: entrack-harmonize-secret
            mountPath: /home/ubuntu/bigg_entrack/.env
            subPath: .env
          - name: entrack-persistent-storage
            mountPath: /mnt/data


      imagePullSecrets:
        - name: registrypullsecret
            
      volumes:
        - name: entrack-harmonize-secret
          secret:
            secretName: entrack-harmonize-secret
            items:
            - key: config.json
              path: config.json
            - key: .env
              path: .env
        - name: entrack-persistent-storage
          persistentVolumeClaim:
            claimName: entrack-claim

